baseURL = "https://alexaworkshop.com/"
ignoreFiles = [ "\\.files/README.md$",  ]
languageCode = "en-us"
defaultContentLanguage = "en"
title = "AWS & Alexa Workshop"
theme = "hugo-theme-learn"
uglyurls = false
sectionPagesMenu = "main"
relativeURLs = true

[blackfriday]
  hrefTargetBlank = true

[params]
  editURL = "https://github.com/aws-samples/aws-alexa-workshop/edit/master/content/"
  themeVariant = "mine"
  showVisitedLinks = false
  author = "Joe SHI"
  description = "AWS & Alexa Workshop"
  disableSearch = false
  disableAssetsBusting = false
  disableShortcutsTitle = true
  branch = "master"
  pygmentsUseClasses = true
  pygmentsCodeFences = true
  pygmentsCodefencesGuessSyntax = true
  pygmentsStyle = "tango"
  uiRepo = "https://github.com/aws-samples/aws-alexa-workshop-smarthome-ui"
  simulatorRepo = "https://github.com/aws-samples/aws-alexa-workshop-smarthome-lamp"
  lambdaRepo = "https://github.com/aws-samples/aws-alexa-workshop-smarthome"

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> GitHub Project"
url = "https://github.com/aws-samples/aws-alexa-workshop"
weight = 30

[[menu.shortcuts]]
name = "<i class='fas fa-envelope'></i> Have questions?"
url = "https://github.com/aws-samples/aws-alexa-workshop/issues"
weight = 40

[Languages]
[Languages.en]
title = "AWS & Alexa Workshop"
weight = 1
languageName = "English"

[Languages.zh]
title = "AWS & Alexa Workshop"
weight = 2
languageName = "简体中文"

[outputs]
home = [ "HTML", "JSON"]
page = [ "HTML" ]